services:
  rbmq: 
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image:  mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db_mongo
  producer:
  ## Exevute leak_engines/git producer
  consumer:
  ## Execute leak_engines/git consumer