---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github_producer.fullname" . }}
  labels:
    {{- include "github_producer.labels" . | nindent 4 }}
type: Opaque
data:
  GH_TOKEN: {{ default "" .Values.secrets.github_token | b64enc | quote }}
  GH_API_KEY: {{ default "" .Values.secrets.github_api_key | b64enc | quote }}
  AQMP_URL: {{ default "" .Values.secrets.aqmp_url | b64enc | quote }}

